ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    publish_tf: true
    use_control: false

    imu0: /imu/data
    imu0_config: [false, false, false,  # Posicion x,y,z
                  true,  true,  false,  # Vel. lineal
                  false, false, true,   # Pos. angular
                  false, false, false,  # Vel. angular
                  true,  true,  true]   # Acel. lineal
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    odom0: /odom
    odom0_config: [false, false, false, # Posicion x,y,z
                   true,  false, false, # Vel. lineal
                   false, false, true,  # Pos. angular
                   false, false, false, # Vel. angular
                   false, false, false] # Acel. lineal
    odom0_differential: false
