slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: true
    map_file_name: "map"
    resolution: 0.05
    publish_map_period: 1.0
    use_scan_matching: true
    mode: "mapping"
    map_start_pose: [0.0, 0.0, 0.0]
